ProjectTaskRecorder/ProjectTaskRecorder/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('jobimport/', include('jobimport.urls')),
    path('admin/', admin.site.urls),
]

ProjectTaskRecorder/jobimport/urls.py
#JobImport/urls.py
from django.urls import path
from . import views

app_name = 'JobImport'
urlpatterns = [
	path( '', views.IndexView.as_view(), name ='index' ),
	#to-do: add in paths once basic views are created 
	#something like path( '<int:job_id>/jobdetails', views.job_details, name='jobdetails' )
	path( '<int:pk>/jobdetails', views.JobDetailsView.as_view() ,name = 'job_details' ),
	path( '<int:pk>/employee_info', views.EmployeeInfoView.as_view(), name = 'employee_info' ),
	path( '<int:pk>/task_info', views.TaskInfoView.as_view(), name = 'task_info' ),
]

ProjectTaskRecorder/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('jobimport/', include('jobimport.urls')),
    path('admin/', admin.site.urls),
]

jobimport/urls.py
#JobImport/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'JobImport'
urlpatterns = [
	path( '', views.IndexView.as_view(), name ='index' ),
	#to-do: add in paths once basic views are created 
	#something like path( '<int:job_id>/jobdetails', views.job_details, name='jobdetails' )
	path( '<int:pk>/jobdetails', views.JobDetailsView.as_view(), name = 'job_details' ),
	path( '<int:pk>/jobview', views.JobView.as_view() ,name = 'job_view' ),
	path( '<int:job_id>/jobupdate', views.JobUpdateView.as_view(), name = 'job_update' ),
	path( '<int:job_id>/jobdelete', views.JobDeleteView.as_view(), name = 'job_delete' ),
	path( '<int:pk>/employee_info', views.EmployeeInfoView.as_view(), name = 'employee_info' ),
	path( '<int:pk>/task_info', views.TaskInfoView.as_view(), name = 'task_info' ),
	path( '<int:pk>/task_update', views.TaskUpdateView.as_view(), name = 'task_update' ),
	path( 'file_upload', views.showfile, name = 'file' ),
	path( 'success', views.SuccessView.as_view(), name = 'success' ),
	path( 'export', views.export, name = 'export' ),
	path( 'employee_export', views.employee_export, name = 'employee_export' ),
	path( 'accumulator', views.AccumulatorView.as_view(), name = 'accumulator' ),
	
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProjectTaskRecorder/jobimport/models.py
import datetime

from django.db import models
from django.utils import timezone
#from jobimport.models import [ModelNames] || import jobimport.models
# Create your models here.
class Employee( models.Model ):
	#class vars, etc.; relates directly to columns
	employee_name = models.CharField(max_length = 200)
	employee_id = models.CharField(max_length = 12)
	#unique id?
	
	#default __str__ func for printing
	def __str__(self):
		return self.employee_name
		

class TaskCodes( models.Model ):
	code_id = models.PositiveSmallIntegerField(default = 0)
	code_desc = models.CharField(max_length = 50)
	
	def __str__(self):
		return self.code_desc
	#more class-unique funcs


class Jobs( models.Model ):
	job_id = models.PositiveSmallIntegerField(default = 0)
	job_name = models.CharField(max_length = 50)
	start_date = models.DateTimeField()
	last_updated = models.DateTimeField( 'Date Updated' )
	
	def __str__(self):
		return self.job_name

jobimport/forms.py
# forms.py, for working on the upload/download functionality 
from django import forms 
from .models import *

class FileForm( forms.ModelForm ):
	class Meta:
		model = File
		fields= ["name", "filepath"]
		
		
class JobForm( forms.ModelForm ):
	job_name = forms.CharField( label='Job name', max_length=25 )
	start_date = forms.DateTimeField( label='Start date', widget=forms.SelectDateWidget(), initial=timezone.now() )
	
	#testing something out...
	#employee_name = forms.MultipleChoiceField( label='Employee name', choices=Employee.objects.all(), widget=forms.SelectMultiple() )
	
	class Meta:
		model = Jobs
		fields = ["job_id", "job_name", "start_date",]
		
	
class TaskForm( forms.ModelForm ):
	code_id = forms.ModelChoiceField( label='Task Code Description', empty_label="Select a Task", queryset=TaskCodes.objects.all(), to_field_name="code_id" )
	actual_budget = forms.DecimalField( label='Actual Budget', min_value=00.00, max_digits=19, decimal_places=2 )
	week_of = forms.DateField( label='Week of', widget=forms.SelectDateWidget(), initial=timezone.now(), required=False)
	
	
	class Meta:
		model = TaskCodes
		fields = ["code_id","actual_budget",]
		
	"""
	def __init__(self, *args, **kwargs):
		super(TaskForm, self).__init__(*args, **kwargs)
		# NOTE: hardcoding it from here works, for whatever reason. Be sure to check the **kwargs value, and how to get this 
		#working properly
		self.fields['code_id'].queryset = TaskCodes.objects.filter(job__job_id=2)
	
	
	
	def save(self, *args, **kwargs):
		tf = super(TaskForm, self).save(commit=False)
		#more to do here?
		if True:
			tf.save(self, *args, **kwargs)
		return tf
	
		TO-DO: more work here, need to force the update. Changing the above to commit=True still doesn't save the change.
		data = self.cleaned_data
		tc.objects.update() 
		Note: current issue invoplved the save() method above; with a type error. This is (possibly) due to the update_fields arg 
		being connected to the MODEL'S save() method, as opposed to the FORM'S. 
		
			Try:
				obj = form.save(commit=False) to get model instance, then call obj.save(update_fields=...)
	"""

ProjectTaskRecorder/jobimport/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
# Create your views here.
#def pagename( request, PK )

#index probably for a base page or something, primarily for testing things out
#think: what are the primary pages for this site going to have?
class IndexView( generic.ListView ):
	template_name = 'jobimport/index.html'
	context_object_name = 'latest_job_list'
	
	def get_queryset(self):
		#return the last X published jobs?
		return Jobs.objects.order_by( '-pub_date' )[:5]
	
	

class JobDetailsView( generic.DetailView ):
	model = Jobs
	template_name = 'jobimport/jobdetails.html'
	
	
class EmployeeInfoView( generic.DetailView ):
	model = Employee
	template_name = 'jobimport/employee_info.html'
	
	
class TaskInfoView( generic.DetailView ):
	model = TaskCodes 
	template_name = 'jobimport/task_info.html'

jobimport/views.py
import os
import tablib
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.db.models import Sum
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.conf import settings 
from django.views.decorators.http import require_POST
from tablib import Dataset
from .resource import *


# Create your views here.
# def pagename( request, PK )

# index probably for a base page or something, primarily for testing things out
# think: what are the primary pages for this site going to have?
""" testing something out for the exporting of data (trying to have it be on the same page as file upload...)"""
def export( request ):
	# default testing with the Task Code file, would need some kind of selection for data set
	code_resource = CodeResource()
	dataset = code_resource.export()
	response = HttpResponse( dataset.csv, content_type='text/csv' )
	response['Content-Disposition'] = 'attachment; filename="task_codes.csv"'
	return response

""" temp function specifically for the employee export functionality, will need to be condensed into once func/class later"""	
def employee_export( request ):
	employee_resource = EmployeeResource()
	dataset = employee_resource.export()
	response = HttpResponse( dataset.csv, content_type='text/csv' )
	response['Content-Disposition'] = 'attachment; filename="employees.csv"'
	return response


def showfile( request ):
	# note: will need to change some of the names around, due to this only working with one upload model/type
	lastfile = File.objects.last()
	filepath = lastfile.filepath
	filename = lastfile.name
	form = FileForm( request.POST or None, request.FILES or None )
	if form.is_valid():
		form.save()
	context = { 'filepath': filepath, 
				'form': form,
				'filename': filename,
			  }
	if request.method == 'POST':

		dataset = tablib.Dataset('')
		new_file = request.FILES['myfile']
		# checking for the file name, to create the appropriate resource object
		if 'employee' in new_file.name:
			dataset.headers = ('Employee', 'Name', 'job')
			employee_resource = EmployeeResource()
			
			imported_data = dataset.load( new_file.read() )
			# testing the imported data before actually uploading it
			result = employee_resource.import_data( dataset, dry_run=True, raise_errors=True )
			context.update( {'result': result.has_errors()} )
			
			if not result.has_errors():
				employee_resource.import_data( dataset, dry_run=False )
				return render( request, 'jobimport/success.html' )
				
		# note: change 'footage' to 'units' later
		if 'codes' in new_file.name:
			dataset.headers = ('Task Code', 'Task Description', 'job', 'footage', 'budget', )
			code_resource = CodeResource()
			
			imported_data = dataset.load( new_file.read() )
			# testing the imported data before actually uploading it
			result = code_resource.import_data( dataset, dry_run=True, raise_errors=True )
			context.update( {'result': result.has_errors()} )
			
			if not result.has_errors():
				code_resource.import_data( dataset, dry_run=False )
				return render( request, 'jobimport/success.html' )

	return render( request, 'jobimport/file.html', context )
	

class IndexView( generic.ListView ):
	template_name = 'jobimport/index.html'
	context_object_name = 'latest_job_list'
	
	def get_queryset(self):
		#return the last X published jobs?
		return Jobs.objects.order_by( '-last_updated' )[:5]
	
	

""" Job-related views """
class JobDetailsView( generic.CreateView ): 
	model = Jobs
	template_name = 'jobimport/jobdetails.html'
	context_object_name = 'job_list'
	form_class = JobForm
	success_url = 'jobview'

	
class JobUpdateView( generic.UpdateView ): 
	model = Jobs
	#fields = ('job_name', 'start_date',)
	form_class = JobForm
	second_form_class = TaskForm
	template_name = 'jobimport/job_update.html'
	context_object_name = 'job_list'
	success_url = 'jobview'
	
	
	def get_context_data(self, **kwargs):
		context = super(JobUpdateView, self).get_context_data(**kwargs)
		context['modelTwo'] = TaskCodes.objects.filter(job__job_id=self.kwargs['job_id'])
		if 'form' not in context:
			context['form'] = self.form_class(initial={'job_id': context['Jobs'].job_id})
			
		if 'formTwo' not in context:
			context['formTwo'] = self.second_form_class()
			context['formTwo'].fields['code_id'].queryset = TaskCodes.objects.filter(job__job_id=self.kwargs['job_id'])
		return context
		
	
	def get_object(self, queryset=None):
		#obj = Jobs.objects.get(job_id=self.kwargs['job_id'])
		return self.model.objects.get(job_id=self.kwargs['job_id'])
		

	def form_valid(self, form):
		"""TO-DO: code here, possibly for the saving, etc."""
		# both return the object (job) name - test. 
		#form.instance.actual_budget = form.fields['actual_budget']
		print( 'printing the form fields: %s\n\n' % form.fields )
		if 'code_id' in form.fields:
			print('did we end up in here?')
			self.object = TaskCodes.objects.get(job__job_id=self.kwargs['job_id'])
			self.object.save()
			#self.object = form.save(update_fields=['actual_budget'])
		else:
			print('this is specifically for the job update form')
			self.object = form.save()
		print( 'object after calling save(): %s' % self.object )
		return HttpResponseRedirect(self.get_success_url())


	def form_invalid(self, **kwargs):
		print( self.get_context_data(**kwargs) )
		return self.render_to_response(self.get_context_data(**kwargs))
		
	
	def post(self, request, *args, **kwargs):
		# getting the user instance
		self.object = self.get_object(request)
		# figuring out which form is being submitted, using the form's submit button
		if 'form' in request.POST:
			form_class = self.get_form_class()
			form_name = 'form'
		else:
			#doing this causes the is_valid() call to fail.
			#self.object = TaskCodes.objects.filter(job__job_id=self.kwargs['job_id']).first()
			form_class = self.second_form_class
			form_name = 'formTwo'
			
		form = self.get_form(form_class)
		print('testing the form class: %s and the form name: %s\n also checking some form attributes: %s\n\n' % (form_class, form_name, form.fields) )
		print( 'printing POST data: %s\n\n' % request.POST)
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(**{form_name: form})
		

class JobDeleteView( generic.DeleteView ): 
	model = Jobs
	template_name = 'jobimport/job_delete.html'
	context_object_name = 'job_list'
	success_url = 'jobview'
	
	def get_object(self, queryset=None):
		obj = Jobs.objects.get(job_id=self.kwargs['job_id'])
		return obj


class JobView( generic.ListView ): 
	model = Jobs
	template_name = 'jobimport/job_view.html'
	context_object_name = 'job_list'
	
	def get_queryset(self):
		return Jobs.objects.order_by( 'job_id' )
	
""" END: Job-related views """
	
class EmployeeInfoView( generic.ListView ):
	model = Employee
	template_name = 'jobimport/employee_info.html'
	context_object_name = 'employee'
	
	def get_queryset(self):
		return Employee.objects.all().filter(job__job_id=self.kwargs['pk'])
	
	
class TaskInfoView( generic.ListView ):
	model = TaskCodes
	template_name = 'jobimport/task_info.html'
	context_object_name = 'task'
	budget_sum = TaskCodes.objects.all().aggregate(sum = Sum('actual_budget'))
	
	def get_context_data(self, **kwargs):
		context = super(TaskInfoView, self).get_context_data(**kwargs)
		context.update({'budget_sum': TaskCodes.objects.filter(job__job_id=self.kwargs['pk']).aggregate(sum = Sum('actual_budget'))})
		return context
	
	
	def get_queryset(self):
		return TaskCodes.objects.all().filter(job__job_id=self.kwargs['pk'])


class TaskUpdateView( generic.FormView ):
	model = TaskCodes
	form_class = TaskForm
	template_name = 'jobimport/task_update.html'
	context_object_name = 'task_list'
	success_url = 'jobview'
	

	"""
		TO-DO: change the get_obj and get_context_data code to properly retrieve the correct data
	"""
	
	def get_context_data(self, **kwargs):
		context = super(TaskUpdateView, self).get_context_data(**kwargs)
		context['form'] = TaskForm()
		if 'form' in kwargs:
			context['form'].fields['code_id'] = TaskCodes.objects.filter(job__job_id=self.kwargs['pk'])
		print(context)
		return context
		
		
	def form_valid(self, form):
		print( 'printing the form fields: %s\n\n' % form.fields )
		if 'code_id' in form.cleaned_data:
			print('did we end up in here?')
			self.object.save()
		return super().form_valid(form)

	


class SuccessView( generic.ListView ):
	template_name = 'jobimport/success.html'
	
	def get_queryset(self):
		return 
	
	
class AccumulatorView( generic.ListView ):
	model = TaskCodes
	template_name = 'jobimport/accumulator.html'
	context_object_name = 'accumulator'
	footage_sum = TaskCodes.objects.all().aggregate(sum = Sum('acc_footage'))
	budget_sum = TaskCodes.objects.all().aggregate(sum = Sum('actual_budget'))
	""" 
	alternatively:
	model = TaskCodes
	template_name and context_object_name remain the same
	footage_sum = Accumulator.objects.all().aggregate(sum = Sum('acc_footage'))
	budget_sum = Accumulator.objects.all().aggregate(sum = Sum('acc_budget'))
	context.update( 'footage_sum': footage_sum, 'budget_sum': budget_sum)
	"""

	def get_context_data(self, **kwargs):
		context = super(AccumulatorView, self).get_context_data(**kwargs)
		context.update({'footage_sum': self.footage_sum, 'budget_sum': self.budget_sum})
		return context
	
	
	def get_queryset(self):
		return TaskCodes.objects.all()

jobimport/templates/jobimport/employee_info.html
<!-- testing for employee_info.html -->
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}
<title>Employee Info</title>

<h1 class="text-center">Employee Information</h1>
<h3 class="text-center">This displays the employees currently assigned.</h3>
<p class="lead text-center">Viewing the employee information for the current job</p>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="{% url 'JobImport:index' %}">Home</a></li>
		<li class="breadcrumb-item"><a href="{% url 'JobImport:job_view' 1 %}">Job List</a></li>
		<li class="breadcrumb-item active" aria-current="page">Employee Information</li>
	</ol>
</nav>

<body>
	<div>
		{% if employee %}
		<table class="table table-bordered table-hover table-sm table-striped">
			<thead class="thead-light">
				<tr>
					<th scope="col">Employee ID</th>
					<th scope="col">Employee Name</th>
				</tr>
			</thead>
			<tbody>
				{% for emp in employee %}
					<tr>
						<td>{{ emp.employee_name }}</td>
						<td>{{ emp.employee_id }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% endif %}
	</div>
	
	<div class="container-fluid">
		<a href="{% url 'JobImport:job_view' 1 %}" class="btn btn-outline-secondary btn-tiny">Back to Job Details</a>
	</div>

</body>
{% endblock %}

jobimport/templates/jobimport/file.html
<!-- file.html -->
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block content %}
<html>
	<head>
		<meta charset="UTF-8">
		<title>Upload Files</title>
	</head>

	<body>
		<h1 class="text-center">File Uploader</h1>
		<h3 class="text-center">This page allows you to upload a file for an existing job</h3>
		<br><br>
		<p class="lead">Click on the "Choose File" button to select a file to upload</p>
		<p>Then, click on the "Upload" button to upload the file.</p>
		<br><br>
		<form enctype="multipart/form-data" method="POST" action="">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<input type="file" name="myfile">
			<br><br>
			<button type="submit">Upload</button>
		</form>
		<br><br>
		<div class="bulk">
			<a href="{% url 'JobImport:export' %}" class="btn btn-outline-secondary btn-tiny">Export Task Codes</a>
			<br><br>
			<a href="{% url 'JobImport:employee_export' %}" class="btn btn-outline-secondary btn-tiny">Export Employees</a>
			<br><br>
			<a href="{% url 'JobImport:index' %}" class="btn btn-outline-secondary btn-tiny">Back to Main Page</a>
			<!-- proof of concept, the below buttons/links should be moved to a more appropriate page after feedback -->
		</div>
		</p>
	</body>
</html>

{% endblock %}

jobimport/templates/jobimport/file_upload.html
<!-- file_upload.html -->
{% extends base.html %}
{% block content %}

<h1> help </h1>

{% endblock %}

jobimport/templates/jobimport/index.html
<!-- testing for index.html -->
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block content %}
<html>
	<head>
		<title>Home Page</title>
	</head>

	<body>
		<div>
			<img src="{% static 'jobimport/test_img.jpg' %}">
			<h1 class="text-center">Welcome to the landing page!</h1>
			<br>
			<div class="alert alert-info" role="alert">
				<h4 class="text-center">If a job was created but is missing files for it, click on the "Upload New Files" button!</h4>
			</div>
			<br>
		</div>
		<div class ="bulk">
			<h4>Getting Started:</h4>
				<p class="lead">Clicking on the "Job Information" button will take you to the Job Info page, wherein you can do the following:</p>
				<li>Create a new job</li>
				<li>Update the information in a current job</li>
				<li>Delete a job</li>
				<li>View employee and task code information on the currently-created jobs</li>
				<br>
				<p>Click below and let's go!</p>
				<br>
				<a href="{% url 'JobImport:job_view' 1 %}" class="btn btn-outline-secondary btn-tiny">Job Information</a>
				<a href="{% url 'JobImport:file' %}" class="btn btn-outline-secondary btn-small">Upload New Files</a>
		</div>
		
	</body>
</html>
{% endblock %}

jobimport/templates/jobimport/job_view.html
<!-- job_view.html, for viewing info about the jobs in the queryset/DB -->
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %} 
<title>Job Info</title>

<body>
	<h1 class="text-center">Job Information</h1>
	<h3 class="text-center">These are the jobs currently open</h3>
	<p class="lead text-center">To update or delete one of these jobs, please click on the respective links for "Update" or "Delete"</p>
	<br>
	
	<div class="alert alert-info" role="alert">
		<h4 class="text-center">Important information!</h4>
		<li class="text-center">To view the Employee information, click on the "View Employees" link.</li>
		<li class="text-center mb-0">To view the Task Code information, click on the "View Task Information" link.</li>
	</div>
	
	<div>
		{% if job_list %}
			<table class="table table-bordered table-hover table-sm table-striped">
				<thead class="thead-light">
					<tr>
						<th scope="col">Job Name</th>
						<th scope="col">Job ID</th>
						<th scope="col">Start Date</th>
						<th scope="col">Last Updated</th>
						<th scope="col"></th>
						<th scope="col"></th>
						<th scope="col"></th>
						<th scope="col"></th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					{% for job in job_list %}
						<tr>
							<td>{{ job.job_name }}</td>
							<td>{{ job.job_id}}</td>
							<td>{{ job.start_date }}</td>
							<td>{{ job.last_updated }}</td>
							<!-- for getting the foreign key value for Jobs objects: 
							<li>test: {{ job.employee }}</li>
							-->
							<td><a href="{% url 'JobImport:job_update' job.job_id %}">Update<a></td>
							<td><a href="{% url 'JobImport:task_update' job.job_id %}">Budget Update Test</a></td>
							<td><a href="{% url 'JobImport:job_delete' job.job_id %}">Delete</a></td>
							<br>
							<td><a href="{% url 'JobImport:employee_info' job.job_id %}">View Employees</a></td>
							<td><a href="{% url 'JobImport:task_info' job.job_id %}">View Task Information</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% endif %}

	</div>

	<div class="container-fluid">
		<a href="{% url 'JobImport:index' %}" class="btn btn-outline-secondary btn-tiny">Back to Main Page</a>
		<a href="{% url 'JobImport:job_details' 1 %}" class="btn btn-outline-secondary btn-tiny">Create New Job</a>
	</div>
	
</body>
{% endblock %}

jobimport/templates/jobimport/jobdetails.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %} 
<body>

	<h1 class="text-center">Job Creation</h1>
	<h3 class="text-center">Use the form below to create a new job in the site</h3>
	<br>
	<div class="alert alert-info" role="alert">
		<h4 class="text-center">Job Creation Steps:</h4>
		<p class="text-center mb-0">1. Put in the ID number for this job</p>
		<p class="text-center mb-0">2. Put in the desired name for this job</p>
		<p class="text-center mb-0">3. Choose a start date for this job</p>
		<p class="text-center mb-0">4. Click the "Create" button!</p>
		<p class="text-center"> You'll be redirected to a success page afterward.</p>
	</div>
	
	<div>
		<form enctype="multipart/form-data" method="POST" action="">
			{% csrf_token %}
			{{ form.as_p }}
			<br><br>
			<button type="submit">Create</button>
			
		</form>
		<br>
	</div>
	<div class="bulk">
		<br><br><br><br>
		<a href="{% url 'JobImport:job_view' 1 %}" class="btn btn-outline-secondary btn-tiny">Back to Job Details</a>
		<a href="{% url 'JobImport:file' %}" class="btn btn-outline-secondary btn-small">Upload New Files</a>
	</div>
	
</body>
{% endblock %}

jobimport/templates/jobimport/success.html
<!-- success.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}

<h1>Welcome to the Success page!</h1>
<p>This is a temp page that exists solely to confirm that certain aspects of the application are working!</p>
<p>Primarily for testing purposes.</p>

<div class="bulk">
	<a href="{% url 'JobImport:index' %}" class="btn btn-outline-secondary btn-tiny">Back to Main Page</a>
</div>

{% endblock %}

jobimport/templates/jobimport/task_info.html
<!-- testing for task_info.html -->
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}
<title>Task Info</title>

<h1 class="text-center">Task Information</h1>
<h3 class="text-center">This displays the current tasks listed for the associated job you cliked on.</h3>
<p class="lead text-center">Viewing task information for the current job</p>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="{% url 'JobImport:index' %}">Home</a></li>
		<li class="breadcrumb-item"><a href="{% url 'JobImport:job_view' 1 %}">Job List</a></li>
		<li class="breadcrumb-item active" aria-current="page">Task Information</li>
	</ol>
</nav>

<body>
	<div>
		{% if task %}
		<table class="table table-bordered table-hover table-sm table-striped">
			<thead class="thead-light">
				<tr>
					<th scope="col">Task Code</th>
					<th scope="col">Task Description</th>
					<th scope="col">Job ID</th>
					<th scope="col">Job Name</th>
					<th scope="col">Total Footage</th>
					<th scope="col">Actual Footage</th>
					<th scope="col">% Footage</th>
					<th scope="col">Total Budget</th>
					<th scope="col">Actual Budget</th>
					<th scope="col">% Budget</th>
				</tr>
			</thead>
			<tbody>
				{% for t in task %}
					<tr>
						<td>{{ t.code_id }}</td>
						<td>{{ t.code_desc }}</td>
						<td>{{ t.job.job_id }}</td>
						<td>{{ t.job.job_name }}</td>
						<td>{{ t.footage }}</td>
						<td>{{ t.actual_footage }}</td>
						<td></td>
						<td>{{ t.budget }}</td>
						<td>{{ t.actual_budget }}</td>
						<td></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<p>Testing functionality of the accumulator: {{ budget_sum.sum }}</p>
		{% endif %}
	</div>
	<div class="container-fluid">
		<a href="{% url 'JobImport:job_view' 1 %}" class="btn btn-outline-secondary btn-tiny">Back to Job Details</a>
	</div>
</body>
{% endblock %}

jobimport/templates/jobimport/task_update.html
<!-- task_update.html -->
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}
<title>Task Update</title>

<body>
	<h1 class="text-center">Task Update Page</h1>
	<h3 class="text-center">This page allows you to update the following:</h3>
	<p class="lead text-center">The Budget and Footage values for the tasks in the current job</p>
	<br>
	<div>
		{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>
		{% endif %}
		
		{% if task_list %}
			<form enctype="multipart/form-data" method="POST" action=""> <!-- not working atm: {% url 'JobImport:task_update' 2 %} -->
				{% csrf_token %}
				{{ form.as_p }}
				<br><br>
				<button type="submit", name="form", value="Submit">Update Task Info</button>
			</form>
		{% endif %}
	</div>
	
	<div class="bulk">
		<br><br><br><br>
		<a href="{% url 'JobImport:job_view' 1 %}" class="btn btn-outline-secondary btn-tiny">Back to Job Details</a>
	</div>
</body>

{% endblock %}